-- ============================================================================
-- PargoParcels — Snowflake platform setup
-- ============================================================================
-- Layered: RAW (landed as-is, including dirt) -> STAGING/MARTS (built by dbt).
-- Improvements over a naive setup:
--   * Files are partitioned year/month only; we CLUSTER BY province in
--     Snowflake instead of partitioning by it on disk (avoids the
--     small-file problem: 36mo x 9 provinces x 4 tables = thousands of files).
--   * TRACKING_EVENTS clustered on (event_date, parcel_id) — it is the 150M-row
--     table and almost every query prunes on date.
--   * Separate LOAD vs TRANSFORM warehouses so a heavy dbt run never
--     starves the ingest path. Auto-suspend 60s — this is a portfolio
--     project, not a credit bonfire.
-- Run as SYSADMIN/SECURITYADMIN.
-- ============================================================================

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS PARGO_LOADER;
CREATE ROLE IF NOT EXISTS PARGO_TRANSFORMER;
CREATE ROLE IF NOT EXISTS PARGO_REPORTER;

USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS PARGO_LOAD_WH
  WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Bulk COPY INTO of parquet landings';
CREATE WAREHOUSE IF NOT EXISTS PARGO_TRANSFORM_WH
  WAREHOUSE_SIZE = 'SMALL'  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'dbt runs';
CREATE WAREHOUSE IF NOT EXISTS PARGO_BI_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Power BI / Tableau / Zoho live queries';

CREATE DATABASE IF NOT EXISTS PARGO_DW;
CREATE SCHEMA IF NOT EXISTS PARGO_DW.RAW;
CREATE SCHEMA IF NOT EXISTS PARGO_DW.STAGING;       -- dbt-managed
CREATE SCHEMA IF NOT EXISTS PARGO_DW.INTERMEDIATE;  -- dbt-managed
CREATE SCHEMA IF NOT EXISTS PARGO_DW.MARTS;         -- dbt-managed
CREATE SCHEMA IF NOT EXISTS PARGO_DW.SNAPSHOTS;     -- dbt SCD2

GRANT USAGE ON DATABASE PARGO_DW TO ROLE PARGO_LOADER;
GRANT USAGE ON DATABASE PARGO_DW TO ROLE PARGO_TRANSFORMER;
GRANT USAGE ON DATABASE PARGO_DW TO ROLE PARGO_REPORTER;
GRANT ALL ON SCHEMA PARGO_DW.RAW TO ROLE PARGO_LOADER;
GRANT USAGE ON SCHEMA PARGO_DW.RAW TO ROLE PARGO_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PARGO_DW.RAW TO ROLE PARGO_TRANSFORMER;
GRANT ALL ON SCHEMA PARGO_DW.STAGING       TO ROLE PARGO_TRANSFORMER;
GRANT ALL ON SCHEMA PARGO_DW.INTERMEDIATE  TO ROLE PARGO_TRANSFORMER;
GRANT ALL ON SCHEMA PARGO_DW.MARTS         TO ROLE PARGO_TRANSFORMER;
GRANT ALL ON SCHEMA PARGO_DW.SNAPSHOTS     TO ROLE PARGO_TRANSFORMER;
GRANT USAGE ON SCHEMA PARGO_DW.MARTS TO ROLE PARGO_REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PARGO_DW.MARTS TO ROLE PARGO_REPORTER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PARGO_DW.MARTS TO ROLE PARGO_REPORTER;
GRANT USAGE ON WAREHOUSE PARGO_LOAD_WH      TO ROLE PARGO_LOADER;
GRANT USAGE ON WAREHOUSE PARGO_TRANSFORM_WH TO ROLE PARGO_TRANSFORMER;
GRANT USAGE ON WAREHOUSE PARGO_BI_WH        TO ROLE PARGO_REPORTER;

-- ============================================================================
-- RAW landing tables (1:1 with source, no constraints — dirt lands here)
-- ============================================================================
USE ROLE PARGO_LOADER;
USE DATABASE PARGO_DW; USE SCHEMA RAW; USE WAREHOUSE PARGO_LOAD_WH;

CREATE FILE FORMAT IF NOT EXISTS FF_PARQUET TYPE = PARQUET;
CREATE STAGE IF NOT EXISTS STG_PARGO_LANDING FILE_FORMAT = FF_PARQUET
  COMMENT = 'PUT local parquet here, or repoint to S3/Azure external stage';

CREATE OR REPLACE TABLE RAW.RETAILERS (
    RETAILER_ID INT, RETAILER_NAME STRING, INDUSTRY STRING, TIER STRING,
    CONTRACT_START_DATE DATE, RATE_PER_PARCEL_ZAR NUMBER(8,2),
    INTEGRATION_TYPE STRING, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE RAW.PICKUP_POINTS (
    PICKUP_POINT_ID INT, STORE_NAME STRING, PARTNER_NAME STRING, PROVINCE STRING,
    CITY STRING, LATITUDE NUMBER(9,6), LONGITUDE NUMBER(9,6), OPENING_DATE DATE,
    CAPACITY_PER_DAY INT, STATUS STRING, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE RAW.COURIERS (
    COURIER_ID INT, COURIER_NAME STRING, REGION STRING, VEHICLE_TYPE STRING,
    HIRED_DATE DATE, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
    CUSTOMER_ID NUMBER, CUSTOMER_NAME STRING, MOBILE_NUMBER STRING, PROVINCE STRING,
    CITY STRING, REGISTRATION_DATE DATE, CUSTOMER_SEGMENT STRING, ACTIVE_FLAG BOOLEAN,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE RAW.ORDERS (
    ORDER_ID NUMBER, CUSTOMER_ID NUMBER, RETAILER_ID INT,
    ORDER_CREATED_AT TIMESTAMP_NTZ, ORDER_VALUE_ZAR NUMBER(10,2), CHANNEL STRING,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE RAW.PARCELS (
    PARCEL_ID NUMBER, ORDER_ID NUMBER, CUSTOMER_ID NUMBER, RETAILER_ID INT,
    PICKUP_POINT_ID INT, COURIER_ID INT, WAYBILL_NUMBER STRING,
    CREATED_AT TIMESTAMP_NTZ, DISPATCHED_AT TIMESTAMP_NTZ,
    ARRIVED_AT_POINT_AT TIMESTAMP_NTZ, NOTIFIED_AT TIMESTAMP_NTZ,
    COLLECTED_AT TIMESTAMP_NTZ, RTS_AT TIMESTAMP_NTZ, PARCEL_STATUS STRING,
    PARCEL_VALUE_ZAR NUMBER(10,2), PARCEL_WEIGHT_KG NUMBER(7,2),
    DELIVERY_COST_ZAR NUMBER(8,2), SERVICE_TYPE STRING, PROVINCE STRING,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP())
  CLUSTER BY (TO_DATE(CREATED_AT), PROVINCE);

CREATE OR REPLACE TABLE RAW.TRACKING_EVENTS (
    TRACKING_EVENT_ID NUMBER, PARCEL_ID NUMBER, EVENT_TYPE STRING,
    EVENT_TIMESTAMP TIMESTAMP_NTZ, LATITUDE NUMBER(9,6), LONGITUDE NUMBER(9,6),
    STATUS STRING, SOURCE_SYSTEM STRING,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP())
  CLUSTER BY (TO_DATE(EVENT_TIMESTAMP));   -- 150M rows at full scale; date pruning is everything

CREATE OR REPLACE TABLE RAW.RETURNS (
    RETURN_ID NUMBER, PARCEL_ID NUMBER, RETAILER_ID INT,
    RETURN_INITIATED_AT TIMESTAMP_NTZ, RETURN_REASON STRING,
    RETURN_VALUE_ZAR NUMBER(10,2), DROP_OFF_POINT_ID INT,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

-- ============================================================================
-- Load: PUT then COPY (run snowsql / or use load_snowflake.py)
-- ============================================================================
-- PUT file:///path/to/data/raw/retailers.parquet @STG_PARGO_LANDING/retailers/;
-- PUT file:///path/to/data/raw/parcels/year=*/month=*/*.parquet @STG_PARGO_LANDING/parcels/ PARALLEL=8;
-- ... etc

COPY INTO RAW.RETAILERS (RETAILER_ID, RETAILER_NAME, INDUSTRY, TIER, CONTRACT_START_DATE, RATE_PER_PARCEL_ZAR, INTEGRATION_TYPE)
  FROM @STG_PARGO_LANDING/retailers/ FILE_FORMAT = FF_PARQUET MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW.PICKUP_POINTS (PICKUP_POINT_ID, STORE_NAME, PARTNER_NAME, PROVINCE, CITY, LATITUDE, LONGITUDE, OPENING_DATE, CAPACITY_PER_DAY, STATUS)
  FROM @STG_PARGO_LANDING/pickup_points/ FILE_FORMAT = FF_PARQUET MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW.COURIERS (COURIER_ID, COURIER_NAME, REGION, VEHICLE_TYPE, HIRED_DATE)
  FROM @STG_PARGO_LANDING/couriers/ FILE_FORMAT = FF_PARQUET MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW.CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, MOBILE_NUMBER, PROVINCE, CITY, REGISTRATION_DATE, CUSTOMER_SEGMENT, ACTIVE_FLAG)
  FROM @STG_PARGO_LANDING/customers/ FILE_FORMAT = FF_PARQUET MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW.ORDERS (ORDER_ID, CUSTOMER_ID, RETAILER_ID, ORDER_CREATED_AT, ORDER_VALUE_ZAR, CHANNEL)
  FROM @STG_PARGO_LANDING/orders/ FILE_FORMAT = FF_PARQUET MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW.PARCELS (PARCEL_ID, ORDER_ID, CUSTOMER_ID, RETAILER_ID, PICKUP_POINT_ID, COURIER_ID, WAYBILL_NUMBER, CREATED_AT, DISPATCHED_AT, ARRIVED_AT_POINT_AT, NOTIFIED_AT, COLLECTED_AT, RTS_AT, PARCEL_STATUS, PARCEL_VALUE_ZAR, PARCEL_WEIGHT_KG, DELIVERY_COST_ZAR, SERVICE_TYPE, PROVINCE)
  FROM @STG_PARGO_LANDING/parcels/ FILE_FORMAT = FF_PARQUET MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW.TRACKING_EVENTS (TRACKING_EVENT_ID, PARCEL_ID, EVENT_TYPE, EVENT_TIMESTAMP, LATITUDE, LONGITUDE, STATUS, SOURCE_SYSTEM)
  FROM @STG_PARGO_LANDING/tracking_events/ FILE_FORMAT = FF_PARQUET MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RAW.RETURNS (RETURN_ID, PARCEL_ID, RETAILER_ID, RETURN_INITIATED_AT, RETURN_REASON, RETURN_VALUE_ZAR, DROP_OFF_POINT_ID)
  FROM @STG_PARGO_LANDING/returns/ FILE_FORMAT = FF_PARQUET MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
