version: 2

sources:
  - name: raw
    database: PARGO_DW
    schema: RAW
    tables:
      - name: DIM_COURIERS
      - name: DIM_CUSTOMERS
      - name: DIM_PICKUP_POINTS
      - name: DIM_RETAILERS
      - name: FACT_ORDERS
      - name: FACT_PARCELS
      - name: FACT_TRACKING_EVENTS
      - name: FACT_RETURNS
